services:
  database:
    image: banking-database-postgres
    pull_policy: never
    container_name: banking-database-postgres
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - banking-nestjs-postgres:/var/lib/postgresql/data
    env_file:
      - ./database/database.env
    ports:
      - 5432:5432

volumes:
  banking-nestjs-postgres: